FROM    pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime

LABEL   author=uros.pascinski@fri.uni-lj.si

WORKDIR /app

COPY    ./requirements-api.txt  /app/
COPY    ./src/api/              /app/src/api/
COPY    ./src/eval/predict.py   /app/src/eval/

RUN     pip install -r requirements-api.txt

ENV     FLASK_APP="src.api" \
        PYTHONPATH="/app"

EXPOSE  5000

ENTRYPOINT  ["flask", "run"]
CMD         ["--host=0.0.0.0", "--port=5000"]
